<?php

/** @var $block \Tigren\CustomerGroupCatalog\Block\CustomerID */

$customerId = $block->getCustomerId();
$postsViewModel = $block->getData('posts_view_model');
$collection = $postsViewModel->getPosts($customerId);

$productRepository = $block->getProductRepository();
$customerRepository = $block->getCustomerRepository();
$orderRepository = $block->getOrderRepository();

$ruleId = 1;

?>
<?php if (!$collection->count()): ?>
    <p>There are no rules.</p>
<?php else: ?>
    <table border="1" cellpadding="10" cellspacing="0">
        <thead>
        <tr>
            <th>ID</th>
            <th>Product Name</th>
            <th>Customer Name</th>
            <th>Order Number</th>
            <th>Rule Name</th>
            <th>Create At</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($collection as $rule): ?>
            <?php
            try {
                $product = $productRepository->getById($rule->getData('product_id'));
                $productName = $product->getName();
                $productUrl = $block->getUrl('catalog/product/view', ['id' => $product->getId()]);
            } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
                $productName = 'Unknown Product';
                $productUrl = '#';
            }

            try {
                $customer = $customerRepository->getById($rule->getData('customer_id'));
                $customerName = $customer->getFirstname() . ' ' . $customer->getLastname();
            } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
                $customerName = 'Unknown Customer';
            }

            try {
                $order = $orderRepository->get($rule->getData('order_id'));
                $orderUrl = $block->getUrl('sales/order/view', ['order_id' => $order->getEntityId()]);
                $orderNumber = $order->getIncrementId();
            } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
                $orderNumber = 'Unknown Order';
            }
            ?>
            <tr>
                <td><?= $ruleId++; ?></td>
                <td><a href="<?= $productUrl; ?>" target="_blank"><?= $productName; ?></a></td>
                <td><?= $customerName; ?></td>
                <td><a href="<?= $orderUrl; ?>" target="_blank"><?= $orderNumber; ?></a></td>
                <td>
                    <a href="<?= $block->getUrl('rule/index/rule'); ?>">
                        <?= $rule->getData('rule_id'); ?>
                    </a>
                </td>

                <td><?= $rule->getData('created_at'); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
<div class="simple-widget">
    <button class="toggle-button">Show/Hide Content</button>
    <div class="toggle-content" style="display:none;">
        <p>This is the content that will be toggled on button click.</p>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'tigren/tigrenWidget'], function ($) {
        $(document).ready(function () {
            $('.simple-widget').tigrenWidget();
        });
    });
</script>

