<?php

use Tigren\Testimonial\Model\Post;
use Tigren\Testimonial\ViewModel\Post\PostView;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Post $post */
/** @var PostView $postView */
/** @var Template $block */
/** @var Escaper $escaper */

$postView = $block->getData('post_view_model');
$post = $postView->getPost();
?>
<h1><?= $escaper->escapeHtml($post->getData('name')); ?></h1>
<?php if ($post->hasData('profile_image')): ?>
    <img src="<?= $escaper->escapeUrl($postView->getPostImage($post)); ?>"
         alt="<?= $escaper->escapeHtmlAttr($post->getData('name')); ?>"
         loading="lazy" />
<?php endif; ?>
<div>
    <span class="email"><?= $escaper->escapeHtml($post->getData('email')); ?></span>
</div>
<div>
    <span class="message"><?= $escaper->escapeHtml($post->getData('message')); ?></span>
</div>
<div>
    <span class="company"><?= $escaper->escapeHtml($post->getData('company')); ?></span>
    <span class="rating"><?= $escaper->escapeHtml($post->getData('rating')); ?></span>
    <span class="created_at"><?= $escaper->escapeHtml($block->formatDate($post->getData('created_at'))); ?></span>
</div>
<p><?= $post->getData('content'); ?></p>
